"""
EvidenceLens — Verdict Engine Service.

Responsibility: synthesize atomic claim verdicts and evidence into a single
top-level verdict with confidence and uncertainty notes.

Verdict logic (target):
  SUPPORTED            — all atomic claims have supporting evidence, none contradicted
  CONTRADICTED         — majority of claims are directly contradicted
  MIXED                — some claims supported, others contradicted
  INSUFFICIENT_EVIDENCE — not enough evidence to decide

Current state: DEVELOPMENT MOCK
  Returns deterministic demo verdicts so the pipeline can be tested end-to-end.

TODO (Phase 2):
  - Implement scoring logic based on evidence relationship and confidence.
  - Optionally use Gemini for a final reasoning pass.
  - Incorporate media_analysis.context_mismatch into the verdict.
"""

from __future__ import annotations

import logging
import uuid

from app.schemas.claim import (
    AnalyzeResponse,
    AtomicClaim,
    EvidenceItem,
    MediaAnalysis,
    Relationship,
    Verdict,
)

logger = logging.getLogger(__name__)

# ─── Public interface ─────────────────────────────────────────────────────────

async def verify(
    claims: list[AtomicClaim],
    evidence: list[EvidenceItem],
    media_analysis: MediaAnalysis | None,
) -> AnalyzeResponse:
    """
    Produce a final AnalyzeResponse by combining atomic claim verdicts,
    retrieved evidence, and media analysis results.

    Args:
        claims:         Atomic claims from the ClaimExtractor.
        evidence:       Evidence items from the EvidenceRetriever.
        media_analysis: Media analysis result, or None if no media was uploaded.

    Returns:
        A fully populated AnalyzeResponse.
    """
    logger.info(
        "Computing verdict for %d claims with %d evidence items",
        len(claims),
        len(evidence),
    )

    # TODO: replace with real scoring in Phase 2
    return _mock_verify(claims, evidence, media_analysis)


# ─── Mock (development only) ──────────────────────────────────────────────────

def _mock_verify(
    claims: list[AtomicClaim],
    evidence: list[EvidenceItem],
    media_analysis: MediaAnalysis | None,
) -> AnalyzeResponse:
    """
    ⚠️  DEVELOPMENT MOCK — not real verdict computation.
    Returns a deterministic MIXED verdict for demonstration purposes.
    Replace with real scoring logic in Phase 2.
    """
    # Update atomic claim verdicts deterministically based on position
    updated_claims: list[AtomicClaim] = []
    for i, claim in enumerate(claims):
        verdict = Verdict.SUPPORTED if i % 2 == 0 else Verdict.MIXED
        updated_claims.append(
            AtomicClaim(
                id=claim.id,
                text=claim.text,
                verdict=verdict,
                confidence=0.91 if verdict == Verdict.SUPPORTED else 0.65,
            )
        )

    # Compute simple top-level verdict
    verdicts = [c.verdict for c in updated_claims]
    if all(v == Verdict.SUPPORTED for v in verdicts):
        top_verdict = Verdict.SUPPORTED
        confidence = 0.91
    elif all(v == Verdict.CONTRADICTED for v in verdicts):
        top_verdict = Verdict.CONTRADICTED
        confidence = 0.88
    elif not verdicts:
        top_verdict = Verdict.INSUFFICIENT_EVIDENCE
        confidence = 0.0
    else:
        top_verdict = Verdict.MIXED
        confidence = 0.72

    uncertainty: list[str] = [
        "⚠️ DEMO MODE: This verdict was generated by the development mock.",
        "Evidence retrieval is not yet connected to a real corpus.",
    ]

    if media_analysis and media_analysis.context_mismatch:
        uncertainty.append(
            "Uploaded media may have been reused out of context — verify independently."
        )

    return AnalyzeResponse(
        claim_id=uuid.uuid4(),
        atomic_claims=updated_claims,
        verdict=top_verdict,
        confidence=confidence,
        evidence=evidence,
        media_analysis=media_analysis,
        uncertainty=uncertainty,
        analyst_notes=None,
    )
